### ISSUE TITLE
[Bug] App crash when starting navigation, then backing out

### ISSUE THREAD

**Issue by dpalencia** [indomie858/app-A#142]
Noticed when I was working on the null entrance location issue

**Comment by indomie858** [comment]
I suspect it's the delayed handler thread continuing to run when you back out. I'll work on this in the morning

**Comment by indomie858** [comment]
I fixed the bug in DirectionsActivity. It was crashing because of the delayed handler thread continuing to run if you start the navigation then back out right away. I added the following handler method call in onDestroy:
> handler.removeCallbacksAndMessages(null);
> Reference: https://stackoverflow.com/questions/5883635/how-to-remove-all-callbacks-from-a-handler

I think this may happen anywhere a handler with a delay is used. Just need to add removeCallbacks to the onDestroy to prevent more crashes. I applied this to DirectoryInformationActivity as well.
